"""empty message

Revision ID: 70e32723c92e
Revises: 716567e95923
Create Date: 2023-08-04 18:45:52.100484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e32723c92e'
down_revision = '716567e95923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee_id', sa.Integer(), nullable=False),
    sa.Column('new_assignee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['new_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_history')
    # ### end Alembic commands ###
